version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "nastavnik"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./configs/db:/docker-entrypoint-initdb.d
      - ~/postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
    container_name: 'app'
    links:
      - postgres
  nginx:
    container_name: 'nginx'
    image: nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    links: 
      - app
  certbot:
    image: certbot/certbot
    volumes:
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot