version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "nastavnik"
      POSTGRES_USER: "postgress"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5442:5432"